#!/bin/sh
FLOATTERM="st -c floating"

# For the values for $1, see the daemon python script 'pytus'. The values are
# the order (1-based) of segments.
case "$1" in
    1) # Memory
        case "$BUTTON" in
            1) UPD=1 ;;
            3) $FLOATTERM -e top -o RES ;;
        esac ;;
    2) # CPU
        case "$BUTTON" in
            3) $FLOATTERM -e top -o %CPU ;;
        esac ;;
    3|vol) # ALSA
        case "$BUTTON" in
            1|mute) amixer -q sset Master toggle; UPD=1 ;;
            3)      $FLOATTERM -e alsamixer ;;
            4|up)   amixer -q sset Master 4%+; UPD=1 ;;
            5|down) amixer -q sset Master 4%-; UPD=1 ;;
        esac ;;
    4|light) # Backlight
        case "$BUTTON" in
            4|up)   brightnessctl -c backlight -q s 4%+ 2> /dev/null; UPD=1 ;;
            5|down) brightnessctl -c backlight -q s 4%- 2> /dev/null; UPD=1 ;;
        esac ;;
    5|imap)
        case "$BUTTON" in
            3) $FLOATTERM mutt ;;
        esac ;;
    6|mpd) # Mpd
        case "$BUTTON" in
            1|pause)    mpc toggle; UPD=1 ;;
            2|stop)     mpc stop; UPD=1 ;;
            3)          $FLOATTERM -e ncmpc ;;
            4|forward)  mpc seek +20 ;;
            5|backward) mpc seek -20 ;;
        esac ;;
    7) # Battery
        case "$BUTTON" in
            1) UPD=1 ;;
        esac ;;
    8) # Network
        case "$BUTTON" in
            1) UPD=1 ;;
            3) $FLOATTERM -e iwctl ;;
        esac ;;
    9) # Date
        ;;
    a) # Notification
        case "${BUTTON-1}" in
            1) dunstctl set-paused toggle; UPD=1 ;;
            3) dunstctl close-all ;;
            4) dunstctl history-pop ;;
            5) dunstctl close ;;
        esac ;;
    b) # Command
        case "${BUTTON-1}" in
            1) rofi -show run ;;
        esac ;;
    c) # Application
        case "${BUTTON-1}" in
            1) rofi -theme launcher -show drun ;;
            3) xmenu-apps ;;
        esac ;;
esac

[ -n "$UPD" ] && pkill -RTMIN+"$1" -f "[0-9 ]*python.*statusd"
