#!/bin/sh
FLOATTERM="st -c floating"

usage() {
    cat << EOF
$(basename "$0") [-h] [N] [vol|light|mpd [command]] [kill]
    -h      show help message
    N       signal Nth segment in the status daemon
    vol     command: mute, up, down
    light   command: up, down
    mpd     command: pause, stop, forward, backward
    kill    kill status daemon
EOF
}

if [ $# = 0 ]; then
    usage
    exit 1
fi

# For the values for $1, see the daemon python script 'pytus'. The values are
# the order (1-based) of segments.
case "$1" in
    1) # Memory
        case "$BUTTON" in
            1) UPD=1 ;;
            3) $FLOATTERM -e top -o RES ;;
        esac ;;
    2) # CPU
        case "$BUTTON" in
            3) $FLOATTERM -e top -o %CPU ;;
        esac ;;
    3)
        case "$BUTTON" in
            1) UPD=1 ;;
            3) $FLOATTERM -e radeontop ;;
        esac ;;
    4|vol) # ALSA
        [ "$1" = vol ] && signal=4 && BUTTON=$2
        case "$BUTTON" in
            1|mute) amixer -q sset Master toggle; UPD=1 ;;
            3)      $FLOATTERM -e alsamixer ;;
            4|up)   amixer -q sset Master 4%+; UPD=1 ;;
            5|down) amixer -q sset Master 4%-; UPD=1 ;;
        esac ;;
    5|light) # Backlight
        [ "$1" = light ] && signal=5 && BUTTON=$2
        case "$BUTTON" in
            4|up)   brightnessctl -c backlight -q s 4%+ 2> /dev/null; UPD=1 ;;
            5|down) brightnessctl -c backlight -q s 4%- 2> /dev/null; UPD=1 ;;
        esac ;;
    6)
        case "$BUTTON" in
            3) $FLOATTERM mutt ;;
        esac ;;
    7|mpd) # Mpd
        [ "$1" = mpd ] && signal=7 && BUTTON=$2
        case "$BUTTON" in
            1|pause)    mpc -q toggle; UPD=1 ;;
            2|stop)     mpc -q stop; UPD=1 ;;
            3)          $FLOATTERM -e ncmpc ;;
            4|forward)  mpc -q seek +20 ;;
            5|backward) mpc -q seek -20 ;;
        esac ;;
    8) # Battery
        case "$BUTTON" in
            1) UPD=1 ;;
        esac ;;
    9) # Network
        case "$BUTTON" in
            1) UPD=1 ;;
            3) $FLOATTERM -e iwctl ;;
        esac ;;
    a) # Date
        ;;
    b) # Notification
        case "$BUTTON" in
            1) dunstctl set-paused toggle; UPD=1 ;;
            3) dunstctl close-all ;;
            4) dunstctl history-pop ;;
            5) dunstctl close ;;
        esac ;;
    c) # Command
        case "$BUTTON" in
            1) rofi -show run ;;
        esac ;;
    d) # Application
        case "$BUTTON" in
            1) rofi -theme launcher -show drun ;;
            3) xdg-xmenu -s 48 ;;
        esac ;;
    kill) pkill -9 -f "python.*statusd"; exit ;;
    -h|--help|*) usage; exit ;;
esac

[ -n "$UPD" ] && statusctl "${signal:-$1}" "${BUTTON}"
